version: '3'
services:
  consumer:
    build: .
    volumes:
      - "c:/projects/github/php-jav-toolbox-api/media:/media"
    environment:
      MESSENGER_TRANSPORT_DSN: amqp://guest:guest@host.docker.internal:5672/%2f/
